#!/bin/sh

# cd into test-cases directory
cd `echo "$0" | sed 's/run-all-unit-tests/test-cases/'`

echo ""
echo " * * * Running all unit tests for 32-bits * * *"

# make clean
../bin/make-recursive.pl clean > /dev/null

# build default architecture
../bin/make-recursive.pl | ../bin/result-filter.pl

# if G5, then also run all test cases built for ppc64
if [ `machine` = "ppc970" ] 
then
	echo ""
	echo " * * * Running all unit tests for 64-bits * * *"
	
	# make clean
	../bin/make-recursive.pl clean > /dev/null

	# build 64-bit architecture
	../bin/make-recursive.pl ARCH="-arch ppc64" | ../bin/result-filter.pl
fi

# if Intel, then also run all test cases under emulation
if [ `sysctl -n hw.machine` = "i386" ] 
then
	echo ""
	echo " * * * Running all unit tests for emulated 32-bits * * *"
	
	# make clean
	../bin/make-recursive.pl clean > /dev/null

	# build ppc architecture
	../bin/make-recursive.pl ARCH="-arch ppc" | ../bin/result-filter.pl
fi

# if 64-bit capable Intel, then also run all test cases for 64-bits
if [ `sysctl -n hw.optional.x86_64` = "1" ] 
then
	echo ""
	echo " * * * Running all unit tests for 64-bits * * *"
	
	# make clean
	../bin/make-recursive.pl clean > /dev/null

	# build x86_64 architecture
	../bin/make-recursive.pl ARCH="-arch x86_64" | ../bin/result-filter.pl
fi
